apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-servers
  labels:
    app: web-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-servers
  template:
    metadata:
      labels:
        app: web-servers
    spec:
      containers:
      - name: node-js
        image: vicky2580/node-js:latest
        ports: 
        - containerPort: 4200
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 50m

---
apiVersion: v1
kind: Service
metadata:
  name: web-servers
  labels:
    app: web-servers
  namespace: default
spec:
  ports:
  - name: web-servers-port
    port: 4200
  selector:
    app: web-servers
  sessionAffinity: None
  type: NodePort



